# Generated by Django 5.2.17 on 2026-09-15 12:27

import django.db.models.deletion
import patients.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_id_str', models.CharField(default=patients.models.generate_health_id, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_id', to='patients.patient')),
            ],
        ),
    ]
