# Generated by Django 5.2.17 on 2026-09-03 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_break_glass', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
