# Generated by Django 5.2.17 on 2026-09-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='scope',
            field=models.JSONField(default=list),
        ),
    ]
